const SENTENCE_FIRST = [
  "En l'ouvrant, il découvre le vélo qu'il rêvait d'avoir!",
  "Le public découvre une chanson inédite créée pour ce soir.",
  "Elle apprend que la sortie est prévue le mois prochain.",
  "La directrice annonce que tous les objectifs sont atteints.",
  "Il découvre le gâteau que sa mère lui a préparé.",
  "Il a gagné deux entrées pour aller au Parc Astérix.",
  "Elle raconte qu'elle attend un bébé.",
  "Il avait fait tomber son billet par terre.",
  "Le parasol est tombé et a cassé la table en verre.",
  "Malheureusement, elle le fit tomber avant son arrivée.",
  "Il ouvrit un restaurant mais il ne recevait aucun client.",
  "Il déménage chez ses parents après avoir perdu son travail.",
  "Quelques mètres avant l'arrivée, un coureur le dépasse.",
  "Il a reçu une boîte de chocolats périmés.",
  "Il apprit qu'il avait échoué à son examen final.",
  "Elle apprit que son chat venait de décéder.",
  "Elle y trouve la clé de son vélo oubliée à l'hôtel.",
  "Il apprend enfin qu'il est admis chez les pompiers.",
  "Karim apprend qu'il aura plus de vacances à Noël.",
  "A minuit, il rentre enfin avec l'animal perdu la veille.",
  "Il découvre que son chat les avait cachées dans sa litière.",
  "Le problème est vite réglé et il arrive à l'heure.",
  "Les indices retrouvés permettent de démasquer l'auteur.",
  "Il a fini par s'allumer, elle n'était pas assez patiente.",
  "C'était l'alarme de l'usine voisine qui était en feu.",
  "L'enquête révèle un défaut de fabrication sur les freins.",
  "Il découvre que sa femme Jade l'avait trahi.",
  "La propriétaire résilie le bail et exige un départ.",
  "Il s'est fait opérer d'appendicite.",
  "Il découvre que son fils a eu un accident avec elle.",
  "Ils découvrent qu'un chat blessé hurlait sur le trottoir.",
  "Son frère les a jetés à la poubelle quand il a pris sa chambre.",
  "Elle doit attendre, mais les statistiques sont favorables.",
  "Son entraîneur lui murmure un mot avec un sourire discret.",
  "Elle le remit dans son sac sans se poser de questions.",
  "Il allait tout lui raconter en arrivant chez elle.",
  "Elle souriait, heureuse de pouvoir vivre cette expérience.",
  "L'émission allait bientôt commencer.",
  "Il sourit en reconnaissant une présence agréable.",
  "Elle l'ouvrit après son repas.",
  "Elle se sent mal à l'aise, sans comprendre pourquoi.",
  "Elle se sent troublée par un détail inattendu.",
  "Il reste déçu face à ce qui semble arriver.",
  "Elle se demande si elle a bien acheté tous les ingrédients.",
  "Il a un mauvais pressentiment, il ne le trouvera peut-être pas.",
  "Elle a peur du résultat final.",
  "Il l'attendait impatiemment.",
  "Elle avait déjà fouillé tout le grenier.",
];

const SENTENCE_SECOND = [
  "Il reste finalement rassuré malgré cette situation.",
  "Elle retrouve peu à peu son calme.",
  "Il continue sans y penser.",
  "Son mari la rassure, il ne peut pas être très loin.",
  "Elle garde son calme avant de se précipiter.",
  "Il a une dizaine d'heures avant la fin.",
  "Il voit au loin la pharmacie, il y est presque.",
  "Elle se dit qu'elle doit juste jouer plus loin.",
  "Elle s'installe à son bureau sans dire un mot.",
  "Les autres avancent sans comprendre où il est parti.",
  "Le bruit persiste et son angoisse ne fait qu'augmenter.",
  "Elle rentre vite, en fermant la porte derrière elle.",
  "Il attend la fin du mois pour savoir s'il la recevra.",
  "Seule Claire réagit et se met à courir derrière elle.",
  "Il s'étire vaguement puis continue sa journée sans y penser.",
  "Personne ne sait s'il est tombé en panne.",
  "Il recule, observe la pièce, puis cherche une autre boîte.",
  "Son téléphone sonne, il décroche, le document reste ouvert.",
  "Les pages tournent lentement sous une lumière douce.",
  "Dans deux minutes, son train arrivera et il partira.",
  "La cuisine sent bon et personne ne parle vraiment.",
  "Le temps passe doucement, sans qu'elle y prête attention.",
  "L'air est doux et on continue sans se presser.",
  "Le soleil chauffe légèrement et tout semble calme.",
  "Un nuage gris s'installe doucement au-dessus de nous.",
  "Une légère inquiétude s'installe en pensant à son amie.",
  "Le bruit d'un verre cassé résonne dans la maison.",
  "Une panne de courant s'installe et on ne le finit pas.",
  "Il le fait tomber sur sa chemise blanche.",
  "Son fils rentre en pleurant, sans vouloir expliquer pourquoi.",
  "Le voisin claque la porte plus fort que d'habitude.",
  "Nicolas repousse son assiette sans avoir presque rien mangé.",
  "Sa sœur l'appelle et ils rient au téléphone un moment.",
  "On s'installe au café d'en face pour patienter.",
  "Son mari lui propose un thé chaud en arrivant.",
  "Nous finissons par jouer aux cartes toute la soirée.",
  "Sa fille lui fait un dessin de la vaisselle pour le réconforter.",
  "Une dame l'invite à partager son parapluie.",
  "Il lui offre un café en s'excusant, ça les fait rire.",
  "Ils tombent sur un petit stand de crêpes en chemin.",
  "Le recruteur lui fait comprendre que ça commence mal.",
  "Elle passe le reste de la soirée gênée et distraite.",
  "Le repas se termine dans un silence froid.",
  "Il doit attendre dehors dans le froid un long moment.",
  "L'écran reste noir malgré plusieurs tentatives de redémarrage.",
  "La salle est pleine et il ne reste que les premiers rangs.",
  "Tout le monde mange en silence, un peu déçu.",
  "Elle range les morceaux sans dire un mot, dépitée.",
];

