const SENTENCE_FIRST = [
  "Sous le sapin, Alex trouve un cadeau mystérieux et bien emballé.",
  "En concert, le chanteur change soudain son programme habituel.",
  "En sortant du ciné, Manon voit l'affiche d'un nouveau film.",
  "En réunion, l'équipe découvre les résultats du projet.",
  "Marc se demande d'où vient la bonne odeur à la maison.",
  "Il lit \"félicitations\" au début du courriel.",
  "Sophie arrive au bureau avec un sourire énigmatique.",
  "Une femme lui tendit de l'argent dans la rue.",
  "Il nage calmement quand il entend un bruit strident.",
  "Elle avait acheté un gâteau pour fêter la bonne nouvelle.",
  "Jules réalisa son rêve depuis qu'il est petit.",
  "Il prépare ses valises pour enfin commencer sa nouvelle vie.",
  "Kevin est en tête du marathon qu'il a tant préparé.",
  "Son parrain a voulu lui acheter un cadeau spécial.",
  "Il consulta ses résultats avec beaucoup d'espoir.",
  "Elle reçut un appel de son père le jour de son anniversaire.",
  "Sarah reçoit une lettre anonyme, épaisse et abîmée.",
  "Il attend son examen médical, décisif pour son avenir.",
  "L'entreprise dévoile enfin sa directive tenue secrète.",
  "Julie attend le retour de son frère parti chercher le chien.",
  "Ali a perdu ses clés depuis plusieurs jours déjà.",
  "La voiture de Léo tombe en panne, il était pressé.",
  "Clara reçoit des menaces anonymes depuis plusieurs semaines.",
  "Elle attendait que son ordinateur s'allume, mais craignait le pire.",
  "Cette nuit, une sirène stridente retentit soudainement.",
  "Personne ne comprend comment la voiture a quitté la route.",
  "Nathan remarque que des documents disparaissent au bureau.",
  "Ils se disputent depuis des semaines au sujet du loyer.",
  "Martin s'absente soudainement pour une chirurgie d'urgence.",
  "La voiture de Gilles a disparu pendant la nuit.",
  "Un cri perçant retentit dans la nuit, sans qu'ils sachent d'où.",
  "Hugo ne sait pas où sont passés ses trophées.",
  "Camille ignore si son équipe marquera le but décisif.",
  "Lucas décroche sa place en finale, sans savoir contre qui il jouera.",
  "Elle trouva un objet qui ne lui appartenait pas.",
  "Mathilde voulait entendre les bonnes nouvelles de son ami.",
  "Elle était sur le point de sauter de l'avion avec son parachute.",
  "Elle courut allumer la radio, elle attendait impatiemment.",
  "Il ouvrit la porte après avoir entendu des voix familières.",
  "Elle reçut une lettre de sa meilleure amie qu'elle attendait.",
  "Ses collègues accueillent Nora avec applaudissements.",
  "La boulangère reçoit un appel très tôt le matin.",
  "Frédéric attend une pluie d'étoile filante pour ce soir.",
  "Amanda prépare un plat surprise pour son frère.",
  "Charles cherche un magasin depuis longtemps.",
  "Marie demande à sa coiffeuse une coupe spéciale.",
  "Il reçoit une invitation de son meilleur ami.",
  "Elle cherchait une photo qu'elle ne retrouvait plus.",
  "Il arrive à l'aéroport et remarque un problème.",
  "Elle touche sa poche et ne sens plus son téléphone.",
  "Eric marche pied nu quand il sent quelque chose sous le pied.",
  "Mafalda ne voit plus son fils dans l'eau de la mer.",
  "Karine semble avoir oublié quelque chose de très important.",
  "Il fait la file pendant des heures, sans savoir s'il arrivera à temps.",
  "Baptiste ne sait pas s'il arrivera avant la fermeture.",
  "Camille n'entend plus les pas de sa fille dans le jardin.",
  "Sophie arrive au bureau en sanglots.",
  "En randonnée, un ami du groupe disparaît sans prévenir.",
  "Théo se réveille la nuit, inquiété par un bruit au couloir.",
  "Lina remarque un fourgon noir garé devant chez elle.",
  "Mathéo craint une facture d'électricité plus élevée.",
  "Brigitte sort en courant du cours de maths, affolée.",
  "Léo a une douleur à son genou qui a déjà été opéré.",
  "Le métro s'est arrêté entre deux arrêts.",
  "Enzo gonfle des ballons et dispose les guirlandes au salon.",
  "Il s'installe pour finir le compte-rendu de la veille.",
  "La lecture du soir s'étire dans le calme de la bibliothèque.",
  "Lorenzo attend en salle d'attente, regardant l'horloge.",
  "On prépare tranquillement le café du dimanche matin.",
  "Elle range ses affaires en écoutant sa musique préférée.",
  "Nous marchons le long de la rivière après le déjeuner.",
  "Il arrose ses plantes comme chaque samedi après-midi.",
  "Nous profitons d'un pique-nique ensoleillé au bord du lac.",
  "Il prépare son sac pour partir en randonnée demain.",
  "Elle chantonne en rangeant la cuisine après le dîner.",
  "On regarde un film tranquillement sous la couverture.",
  "Il savoure son café en lisant le journal du matin.",
  "Elle prépare le goûter pendant que les enfants jouent dehors.",
  "Il range le salon en écoutant une chanson qu'il aime bien.",
  "On finissait de manger et on discutait tranquillement.",
  "Il rentre épuisé après une longue journée de travail.",
  "Nous ratons notre train de justesse ce matin-là.",
  "Il oublie son parapluie et se fait tremper sous la pluie.",
  "On annule notre sortie à cause du mauvais temps.",
  "Il casse son assiette préférée en faisant la vaisselle.",
  "Elle rate son bus et doit attendre le suivant sous la pluie.",
  "Il oublie l'anniversaire de son collègue de bureau.",
  "Le restaurant auquel ils voulaient aller est fermé.",
  "Il rate son bus et arrive en retard à l'entretien.",
  "Elle renverse du vin rouge sur sa robe neuve.",
  "Nous nous disputons encore pour la même histoire de ménage.",
  "Il oublie les clés à l'intérieur et claque la porte.",
  "Elle casse son téléphone en le faisant tomber des escaliers.",
  "On arrive au cinéma alors que la séance a déjà commencé.",
  "Il brûle le repas qu'il préparait pour ses invités.",
  "Elle fait tomber son gâteau en sortant du four.",
];

const SENTENCE_SECOND = [
  "En l'ouvrant, il découvre le vélo qu'il rêvait d'avoir!",
  "Le public découvre une chanson inédite créée pour ce soir.",
  "Elle apprend que la sortie est prévue le mois prochain.",
  "La directrice annonce que tous les objectifs sont atteints.",
  "Il découvre le gâteau que sa mère lui a préparé.",
  "Il a gagné deux entrées pour aller au Parc Astérix.",
  "Elle raconte qu'elle attend un bébé.",
  "Il avait fait tomber son billet par terre.",
  "Le parasol est tombé et a cassé la table en verre.",
  "Malheureusement, elle le fit tomber avant son arrivée.",
  "Il ouvrit un restaurant mais il ne recevait aucun client.",
  "Il déménage chez ses parents après avoir perdu son travail.",
  "Quelques mètres avant l'arrivée, un coureur le dépasse.",
  "Il a reçu une boîte de chocolats périmés.",
  "Il apprit qu'il avait échoué à son examen final.",
  "Elle apprit que son chat venait de décéder.",
  "Elle y trouve la clé de son vélo oubliée à l'hôtel.",
  "Il apprend enfin qu'il est admis chez les pompiers.",
  "Karim apprend qu'il aura plus de vacances à Noël.",
  "A minuit, il rentre enfin avec l'animal perdu la veille.",
  "Il découvre que son chat les avait cachées dans sa litière.",
  "Le problème est vite réglé et il arrive à l'heure.",
  "Les indices retrouvés permettent de démasquer l'auteur.",
  "Il a fini par s'allumer, elle n'était pas assez patiente.",
  "C'était l'alarme de l'usine voisine qui était en feu.",
  "L'enquête révèle un défaut de fabrication sur les freins.",
  "Il découvre que sa femme Jade l'avait trahi.",
  "La propriétaire résilie le bail et exige un départ.",
  "Il s'est fait opérer d'appendicite.",
  "Il découvre que son fils a eu un accident avec elle.",
  "Ils découvrent qu'un chat blessé hurlait sur le trottoir.",
  "Son frère les a jetés à la poubelle quand il a pris sa chambre.",
  "Elle doit attendre, mais les statistiques sont favorables.",
  "Son entraîneur lui murmure un mot avec un sourire discret.",
  "Elle le remit dans son sac sans se poser de questions.",
  "Il allait tout lui raconter en arrivant chez elle.",
  "Elle souriait, heureuse de pouvoir vivre cette expérience.",
  "L'émission allait bientôt commencer.",
  "Il sourit en reconnaissant une présence agréable.",
  "Elle l'ouvrit après son repas.",
  "Elle se sent mal à l'aise, sans comprendre pourquoi.",
  "Elle se sent troublée par un détail inattendu.",
  "Il reste déçu face à ce qui semble arriver.",
  "Elle se demande si elle a bien acheté tous les ingrédients.",
  "Il a un mauvais pressentiment, il ne le trouvera peut-être pas.",
  "Elle a peur du résultat final.",
  "Il l'attendait impatiemment.",
  "Elle avait déjà fouillé tout le grenier.",
  "Il reste finalement rassuré malgré cette situation.",
  "Elle retrouve peu à peu son calme.",
  "Il continue sans y penser.",
  "Son mari la rassure, il ne peut pas être très loin.",
  "Elle garde son calme avant de se précipiter.",
  "Il a une dizaine d'heures avant la fin.",
  "Il voit au loin la pharmacie, il y est presque.",
  "Elle se dit qu'elle doit juste jouer plus loin.",
  "Elle s'installe à son bureau sans dire un mot.",
  "Les autres avancent sans comprendre où il est parti.",
  "Le bruit persiste et son angoisse ne fait qu'augmenter.",
  "Elle rentre vite, en fermant la porte derrière elle.",
  "Il attend la fin du mois pour savoir s'il la recevra.",
  "Seule Claire réagit et se met à courir derrière elle.",
  "Il s'étire vaguement puis continue sa journée sans y penser.",
  "Personne ne sait s'il est tombé en panne.",
  "Il recule, observe la pièce, puis cherche une autre boîte.",
  "Son téléphone sonne, il décroche, le document reste ouvert.",
  "Les pages tournent lentement sous une lumière douce.",
  "Dans deux minutes, son train arrivera et il partira.",
  "La cuisine sent bon et personne ne parle vraiment.",
  "Le temps passe doucement, sans qu'elle y prête attention.",
  "L'air est doux et on continue sans se presser.",
  "Le soleil chauffe légèrement et tout semble calme.",
  "Un nuage gris s'installe doucement au-dessus de nous.",
  "Une légère inquiétude s'installe en pensant à son amie.",
  "Le bruit d'un verre cassé résonne dans la maison.",
  "Une panne de courant s'installe et on ne le finit pas.",
  "Il le fait tomber sur sa chemise blanche.",
  "Son fils rentre en pleurant, sans vouloir expliquer pourquoi.",
  "Le voisin claque la porte plus fort que d'habitude.",
  "Nicolas repousse son assiette sans avoir presque rien mangé.",
  "Sa sœur l'appelle et ils rient au téléphone un moment.",
  "On s'installe au café d'en face pour patienter.",
  "Son mari lui propose un thé chaud en arrivant.",
  "Nous finissons par jouer aux cartes toute la soirée.",
  "Sa fille lui fait un dessin de la vaisselle pour le réconforter.",
  "Une dame l'invite à partager son parapluie.",
  "Il lui offre un café en s'excusant, ça les fait rire.",
  "Ils tombent sur un petit stand de crêpes en chemin.",
  "Le recruteur lui fait comprendre que ça commence mal.",
  "Elle passe le reste de la soirée gênée et distraite.",
  "Le repas se termine dans un silence froid.",
  "Il doit attendre dehors dans le froid un long moment.",
  "L'écran reste noir malgré plusieurs tentatives de redémarrage.",
  "La salle est pleine et il ne reste que les premiers rangs.",
  "Tout le monde mange en silence, un peu déçu.",
  "Elle range les morceaux sans dire un mot, dépitée.",
];

module.exports = { SENTENCE_FIRST, SENTENCE_SECOND };