const SENTENCES = [
  "Il est 4 heures du matin et John est sur le point de s'endormir lorsqu'il entend des coups de feu. Il sursaute de son lit et regarde par sa fenêtre.",
  "Il est 4 heures du matin et Mike s'apprête à aller dormir lorsque soudain il entend un homme crier 'Adieu monde cruel' suivi d'un bruit sourd. Le souffle coupé, il se lève pour se rapprocher de sa fenêtre. Il a à peine le temps de se gratter les paupières qu'il voit son voisin étendu à terre, inerte.",
  "Andy est à son restaurant préféré et à son habitude il commande 'La Surprise du Chef' comme plat principal. Il s'agit d'une préparation dans laquelle le chef choisit les ingrédients qu'il souhaite travailler. Andy espère qu'il va aimer. Un parfum incroyable se dégage du plat surprise. Andy se régale.",
  "Mia se balade avec un ami lorsque soudain il sort un cadeau de son sac. Son ami lui demande si elle aime le papier cadeau.",
  "Bertrand a joué à la loterie en utilisant ses numéros favoris pour tenter de gagner le jackpot de € 4 000 000. Il essaie de regarder le tirage de la loterie à la télé, mais il n'y a pas de signal.",
  "Léonard a envie de manger un bon plat ce soir. Il va à son restaurant préféré.",
  "Quelqu'un toque à la porte de Pierre et dépose un colis inattendu. Pierre ouvre le colis et découvre un parfum offert par sa copine Sara.",
  "Lena doit retirer de l'argent. Elle se rend à la banque près de chez elle.",
  "Bruno rentre chez lui. Il prend son bus.",
  "Connor attend son métro en espérant qu'il ne sera pas trop rempli. Le métro qui arrive en station déborde de gens, Connor arrive à s'y glisser avec difficulté mais il a du mal à respirer.",
  "Comme chaque matin, Sara se balade dans son quartier lorsqu'elle entend quelqu'un chanter bruyamment. Elle regarde derrière d'elle pour comprendre d'où vient cette voix, mais ne voit que des enfants aux alentours.",
  "Leo a commandé un écran sur Amazon. Il reçoit son colis après 2 jours ouvrables comme prévu.",
  "Karen vient de marcher sur quelque chose de collant. Elle regarde sous sa chaussure mais il n'y a rien.",
  "Simon est en train de courir pour attraper son bus lorsque son téléphone sonne. Une voix glaciale lui dit qu'un de ses proches a eu un accident. Simon s'arrête et le bus lui file sous le nez. Il demande qui est à l'appareil mais la ligne se coupe.",
  "Maja marche avec un ami lorsqu'il sort un cadeau de son sac. Elle déballe le cadeau et voit qu'il s'agit du magnifique pull qu'elle voulait depuis des mois.",
  "Robbie se dirige vers le rencard que son meilleur ami lui a arrangé. Selon ce dernier, la fille qu'il va lui presenter est magnifique. En allant au rendez-vous, Robbie est très anxieux et il transpire beaucoup comme à son habitude.",
  "Matt a une copine. Il lui fait beaucoup de cadeaux.",
  "Le train de Kim est retardé. Elle entend qu'il sera retardé de quelques heures à cause d'un problème technique qui affecte les rails de train.",
  "Il est 3 heures du matin et Selma marche vers chez elle. Soudain, elle entend une femme crier et une voiture arriver en trombe. Selma a à peine le temps de comprendre ce qu'il arrive que la voiture la percute. Elle décède sur le coup",
  "Sara marche vers chez elle au milieu de la nuit. Des voitures passent le long de la rue.",
  "Erik vient d'acheter des sneakers super rares et il a hâte de voir la tête de ses amis quand il leur dira ce soir. Les amis d'Erik adorent sa nouvelle paire et le complimentent sur son goût.",
  "Alexandre joue à la loterie chaque semaine. Il achète toujours ses tickets chez le même vendeur.",
  "Emma se balade dans la rue. Elle porte des chaussures bleues.",
  "Lucie marche dans la rue lorsqu'elle voit une personne au loin qui ressemble à son cousin Jérémy. Lucie essaye d'attirer son attention en hurlant son prénom en vain.",
  "Une personne toque à la porte de Jim et dépose un colis inattendu. Jim ouvre sa porte curieux, mais en prenant le colis entre ses mains il réalise qu'il est destiné à son voisin.",
  "Julie reçoit un appel de l'hôpital pour lui rappeler qu'elle a un rendez-vous avec son dentiste. Julie remercie le réceptionniste pour ce rappel.",
  "Tyler adore les sneakers. Il décide d'en acheter une nouvelle paire.",
  "Cam attend son bus en espérant qu'il ne sera pas trop plein. Le bus qui arrive est hors-service, Cam continue à attendre.",
  "Emma est en train de courir dans un parc lorsqu'elle voit un homme au loin qui ressemble à son ami Marcus. Elle commence à courir dans sa direction pour vérifier que ce soit bien lui. Emma se rapproche de l'homme et crie: 'Marcus!'. L'homme se retourne en sursautant et la salue chaleureusement.",
  "Jade se balade avec une amie. Elles parlent de leur journée.",
  "Lorenzo est à son restaurant favoris, il adore y aller car son ami Aaron est le chef. Lorenzo a hâte de goûter ce qu'Aaron va lui préparer vu que chaque fois qu'il mange chez lui il découvre de nouvelles saveurs. L'attente est plus longue que d'habitude, Lorenzo a très faim.",
  "Lukas a un nouveau 'match' sur Tinder. Il ouvre l'application et découvre que c'est la jolie fille qu'il avait 'superliké' plus tôt dans la journée.",
  "Comme tous les matins, Ana sort son chien. Le soleil réchauffe sa peau.",
  "Mike est dans un supermarché lorsqu'un homme cagoulé et armé crie: 'Tout le monde au sol, ceci est un hold-up!' Les jambes de Mike commencent à trembler.",
  "Comme chaque matin, Eva se promène lorsqu'elle entend une personne crier des mots dans une langue étrangère derrière elle. Elle se retourne et voit qu'il s'agit d'un homme bourré qui se met à vomir sur le trottoir.",
  "Matéo est en retard pour aller au travail lorsque son téléphone sonne. Ça alors! On l'appelle toujours au mauvais moment! Il décroche nerveux et une voix froide lui dit qu'un de ses proches a été admis en réanimation à l'hôpital. La voix dit à Matéo que son frère vient d'avoir un grave accident de voiture.",
  "Lena fait son jogging dans un parc. Elle croise beaucoup de gens qui font des pique-niques.",
  "Mina vient de marcher sur quelque chose de collant. Elle regarde sous sa chaussure et voit qu'un chewing-gum est collé à sa semelle.",
  "Nathan a joué à la loterie avec les mêmes numéros qu'il utilise à chaque fois. Cette semaine il pourrait gagner 3 000 000 d'euros. Nathan compare ses numéros avec ceux gagnants...et c'est le Jackpot!!! Il a tout les numéros gagnants, il est maintenant millionnaire!",
  "Liam est à la station et il attend son train matinal. Lorsque le train arrive, il monte dedans.",
  "Sam est sur Tinder. Il croise des profils différents et décide s'il souhaite les 'matcher'.",
  "Ava a acheté un nouveau sac à main de luxe et elle a hâte de le montrer à ses copines. Ava est très satisfaite de son achat et elle s'entraîne à defiler avec dans son salon comme font les stars.",
  "Le bus de Cara est en retard. Elle continue à attendre.",
  "Albert se dirige à un 'blind-date' que son meilleur ami lui a organisé. À ce qu'il paraît la fille qu'il va rencontrer est magnifique. Lorsque Albert la voit arriver, il est immédiatement sous le charme.",
  "Mira rentre chez elle en pleine nuit vers 3 heures du matin lorsqu'elle entend une moto arriver rapidement dans son dos et des cris stridents. Elle se retourne pour regarder ce qu'il se passe.",
  "Arthur fait la file à la banque pour retirer de l'argent quand un homme cagoulé et armé rentre dans le bâtiment. Arthur lâche un cri strident et se fait immédiatement tirer dessus. Il meurt avant d'arriver aux urgences",
  "Max a un nouveau match sur Tinder! Il tente d'ouvrir l'application pour voir de qui il s'agit, mais son téléphone reste figé sur la page d'accueil.",
  "C'est la veille du nouvel an et Mike entend des feux d'artifice toute la nuit. Il met des bouchons d'oreilles pour dormir.",
  "Matéo est en train de courir pour attraper son bus lorsque son téléphone sonne. Une voix glaciale lui dit qu'un de ses proches a eu un accident. Matéo s'arrête et le bus lui file sous le nez. Il demande qui est à l'appareil mais la ligne se coupe.",
  "En sortant de l'école, Justine réalise qu'elle a oublié son téléphone en classe. Elle décide de retourner à l'école pour le récupérer.",
  "Bob regarde une finale de Coupe du Monde, son équipe préférée a des chances de gagner! Bob ne quitte pas l'écran des yeux, jusqu'au moment où son équipe devient enfin Championne du Monde!",
  "Chloé est sur le point de s'endormir lorsque l'avion sur lequel elle voyage commence à faire un bruit sourd depuis le moteur gauche. Après quelques minutes, le pilote dit aux passagers qu'une turbine dans le moteur est déféctueuse mais que cela ne va pas influencer leur trajet. Il ajoute qu'il ne faut pas paniquer.",
  "Kevin est un fervent supporteur de l'équipe nationale de football. Il regarde tous les matchs et connaît les particularités de chaque joueur.",
  "Mady fait la fête au centre-ville. Elle voit beaucoup de personnes qui consomment de l'alcool.",
  "Paul doit rejoindre un ami pour prendre un café. Il monte dans le bus pour se rendre au lieu de rendez-vous.",
  "La valise de Simon, contenant tous ses livres favoris, a été perdue par la compagnie aérienne lors de son dérnier vol. Simon commence à faire la file pour réclamer sa valise aux objets trouvés.",
  "Nelly aimerait adopter un chaton et elle espère en trouver un au refuge de la ville. Lorsqu'elle arrive au refuge, Nelly identifie immédiatement le chaton de ses rêves: un tout noir avec des petites oreilles.",
  "Tom regarde un match de foot avec son équipe préférée, ils pourraient gagner la Champions League! Les deux équipes jouent aussi bien l'une que l'autre, le match est très serré.",
  "Clara est au centre-ville lorsque son père l'appelle inquiet en demandant si elle va bien car une fusillade a éclaté à la gare. Clara essaie de le calmer et lui dit de la lâcher un peu. Il exagère toujours.",
  "Olivia fait un tour touristique lorsque quelque chose de mouillé tombe sur sa tête. Elle touche ses cheveux et comprend qu'un pigeon lui a déféqué dessus.",
  "La maman d'Ethan lui envoie un message en disant qu'elle va lui préparer un bon repas. Curieux, Ethan essaye de l'appeler pour en savoir plus mais son téléphone s'éteint.",
  "Emmanuel est supposé rejoindre son ami pour prendre un verre d'ici peu, donc il décide de vérifier l'heure qu'il est sur son téléphone. Il est 16h30. Vite! Il ne lui reste plus que 10 minutes pour le rejoindre.",
  "Adrien est réveillé par son chien qui aboie en pleine nuit. Il est surpris car son chien n'aboie jamais. Il se dit qu'il devrait descendre vérifier ce qu'il se passe mais il est trop fatigué. Il retourne donc dormir, tant pis si c'est des voleurs.",
  "Irene aimerait voyager mais ne sachant pas où aller, elle décide de demander conseil à une agence de voyages. L'agent lui dit qu'il y a des promotions intéressantes pour Malaga, Barcelone et Rome.",
  "Quelqu'un a dit à Cynthia que l'examen de physique quantique qu'elle redoutait a été annulé. Elle envoie un e-mail à son professeur en lui demandant si c'est bien le cas. Ce dernier lui confirme que l'examen a été supprimé.",
  "Jack rentre chez lui et entend des bruits suspects à l'étage. Il est inquiet car il habite seul. Il marche sur la pointe des pieds en se rapprochant des escaliers.",
  "Eva planifie un city-trip à San Francisco. Elle voudrait trouver un vol pas cher.",
  "Lisa a travaillé assidûment pour sa thèse de master. Elle a eu une très bonne note: 85%!.",
  "Lorena est en retard pour son rendez-vous. Elle s'apprête à sortir mais elle ne trouve pas son téléphone. Elle se souvient soudain qu'elle l'a laissé dans les cabines à la gym ce matin.",
  "Serena entend que son examen d'algèbre a été annulé. Elle espère que ce soit vrai car elle ne comprend rien en cours.",
  "Jeanne fait des activités touristiques. Elle prend beaucoup de selfies.",
  "Jim habite seul et il rentre tous les jours du travail à 19h. Mais vendredi dernier en passant le seuil de sa porte un bruit inquiétant venant de l'étage l'a surpris. Après avoir monté les escaliers en courant, il découvre qu'un oiseau s'est introduit dans sa chambre par la fenêtre et a détruit son vase préféré.",
  "Ivan adore faire du voilier. Il part souvent en navigation pendant l'été.",
  "Justine bronze en pleine mer lorsqu'elle voit une tornade se former au loin. Un frisson parcourt sa colonne vertébrale.",
  "Sam rentre à la maison. Il enlève sa veste.",
  "Kim veut partir en voyage mais elle ne sait pas encore où aller. Elle commence à regarder des destinations sur Google. Elle voit qu'il y a des vols pas chers pour Venise ce week-end et elle en réserve un immédiatement.",
  "Soline a travaillé d'arrache-pied sur son devoir le mois passé. Elle se rend en classe et espère recevoir une très bonne note. Son professeur lui dit qu'il n'a pas encore fini de corriger les devoirs.",
  "Megan est en train de bronzer sur son bateau lorsqu'elle entrevoit une tempête se former à quelques noeuds. Il commence à pleuvoir et elle essaye de s'abriter. Des vagues de plusieurs mètres s'abattent sur le mas du bateau, Megan perd l'équilibre et tombe dans l'eau. Elle se bat contre les vagues pendant plusieurs minutes mais exténuée elle se noie.",
  "Sam se fait réveiller par l'aboiement de son chien en pleine nuit. Il se dit que c'est étrange étant donné que son chien est d'habitude très calme. Il se lève pour aller voir si son chien va bien. Une fois en bas des escaliers, il se gratte les yeux pour être sur de bien voir ce qu'il se passe: son chien a une souris dans la gueule.",
  "Alexandra aimerait adopter un chat et elle espère en trouver un au refuge. Mais elle est inquiète car son chien a mauvais caractère et il pourrait mal réagir à l'arrivée d'un chaton à la maison.",
  "Mona dort paisiblement dans son lit. Elle rêve que son chien court dans le jardin.",
  "Lucille ne trouve pas son portable. Elle regarde partout dans la maison mais il n'y a pas de trace de son téléphone.",
  "Sara a travaillé assidument pour la thèse qu'elle a rendu le mois passé. Elle espère avoir une bonne note. En arrivant en classe son professeur la congratule immédiatement car sa thèse était excellente: Sara a obtenu un 90%!.",
  "Simon est avec un ami lorsqu'il croise une fille avec qui ils ont fait la fête toute la nuit il y a quelques semaines. Ils discutent de tout et de rien.",
  "Laura aimerait adopter un chaton. Elle va sur Internet pour trouver un refuge.",
  "Mara est dans ses pensées lorsque l'avion dans lequel elle voyage perd de l'altitude violemment. Tout le monde commence à hurler. L'hôtesse de l'air la plus proche s'évanouit.",
  "Elena fait du tourisme lorsqu'elle sent quelque chose de chaud tomber sur son épaule. Elle regarde son épaule mais il n'y a rien dessus.",
  "Nick reçoit un message de sa maman qui lui dit qu'elle a préparé un bon repas pour lui. Nick rentre avec hâte à la maison et découvre qu'elle lui a fait une pizza, son plat préféré.",
  "La valise de Marco, contenant tous ses habits favoris, a été perdue lors de son voyage en avion. Marco reçoit un appel de la compagnie d'avion lui disant qu'ils sont dans l'incapacité de trouver sa valise et qu'il sera remboursé à la hauteur de 300 euros pour les dommages occasionnés.",
  "La maman de Kevin lui envoie un message en lui demandant ce qu'il voudrait manger pour le dîner. Il lui répond qu'il aimerait des lasagnes.",
  "Karl est avec un ami lorsqu'ils croisent une fille avec qui ils ont passé la soirée il y a quelques semaines. Karl s'efforce de se rappeler son prénom mais n'y parvient pas. Il continue de discuter avec elle comme si de rien n'était.",
  "Theo prend l'avion pour partir en vacances. Il a préparé une grande valise avec tous ses habits préférés.",
  "Mario est avec un ami lorsqu'ils croisent une fille avec qui ils sont sortis en soirée mais il ne se rappelle plus du prénom de cette fille. L'ami de Mario lui glisse discrètement à l'oreille qu'elle s'appelle Diana.",
  "Elena est de sortie en ville lorsque sa mère l'appelle en panique pour lui demander si elle est bien en sécurité. Elle poursuit confuse en criant que quelque chose d'horrible vient d'arriver au centre-ville. La mère d'Élena lui dit qu'il y a eu une attaque à la bombe et qu'elle doit rentrer à la maison le plus vite possible.",
  "Erin voyage en avion. Elle a bouclé sa ceinture.",
  "Mara a bientôt un examen de la plus haute importance. Elle passe toutes ses journées à la bibliothèque.",
  "Magnus doit rejoindre son ami pour prendre un café, il décide de regarder l'heure sur son portable. Magnus sort son téléphone mais sa batterie est à plat."
];


const sent_length = [
  "Léo ouvre son cadeau et sourit avec joie.",
   "Sarah attend son train depuis plusieurs minutes lorsqu'une musicienne commence à jouer du violon sur le quai. Les voyageurs s'arrêtent un instant pour écouter cette mélodie apaisante.",
   "Thomas se promène dans le centre-ville après une longue journée de travail lorsqu'il remarque une petite librairie qu'il n'avait jamais vue auparavant. Curieux, il entre et parcourt les rayons remplis de romans et d'essais. Après quelques minutes, il découvre un livre qui correspond parfaitement à ses centres d'intérêt et décide de l'acheter immédiatement pour le lire pendant le week-end."
]